
        var endpoint,key,authSecret;
        var appConfig={
          server_url:"https://ungdungquanly.vn",
          server_url_report:"https://ungdungquanly.vn",
          print_service_url:"http://localhost:8989/web-print",
          id_app:"",
          group_id:"",
          public_token:"",
          app_title:"zCAFE",
          app_name:"zCAFE",
          app_name_en:"zCAFE",
          sologan_en:"",
          sologan:"",
          app_description:"",
          app_address:"",
          app_phone:"",
          app_email:"info@ungdungquanly.vn",
          primaryColor:"#0E52A1",
          secondaryColor:"#52A20E",
          mainColor:"#013659",
          titleColor:"#0E52A1",
          iconColor:"#52A20E",
          progressColor:"#592401",
          mainTextColor:"#fff",
          printPageWidth:"302",
          GOOGLE_MAPS_APIKEY:"",
          GOOGLE_RECAPTCHA_SITE_KEY:"6LfC5rAUAAAAAASnfRem8Q0Ame4KccFp0b9Twa8N",
          menu:[
            {"code":"banhang","title":"Bán hàng","path":"/banhang","group":"Bán hàng"},
            {"code":"bepmonitor","title":"Các món đang chờ","path":"/kitchen-monitor","group":"Bán hàng"},
            {"code":"giaoca","title":"Giao ca","path":"/list/giaoca","group":"Bán hàng"},
            {"code":"pbl","title":"Bảng kê phiếu bán hàng","path":"/voucher/pbl","group":"Bán hàng"},
            {"code":"dmkho","title":"Khai báo cửa hàng","path":"/list/dmkho","group":"Cài đặt"},
            {"code":"dmnvt","title":"Khai báo sản phẩm","path":"/list/dmnvt","group":"Cài đặt"},
            {"code":"customer","title":"Khai báo khách hàng","path":"/list/customer","group":"Cài đặt"},
            {"code":"note","title":"Danh sách ghi chú sẵn","path":"/list/note?id_link=PBL","group":"Cài đặt"},
          ]
        }
